---
title: "Korean Analysis"
author: "ssang"
date: '2020 7 17 '
output: html_document
---

# 한국 복지 패널 데이터 분석 
---
## 데이터 수집 및 준비

https://www.koweps.re.kr:442


## 데이터  준비

#### 1-1 라이브러리 준비
```{r}
# install.packages("foreign")
# install.packages("dplR")
# install.packages("ggplot2")
# install.packages("readxl")
library(foreign)
library(ggplot2)
library(readxl)
```

#### 1-2 데이터 불러오기 
```{r}
raw_welfare <- read.spss("../data/Koweps_hpc10_2015_beta1.sav",to.data.frame="T")
head(raw_welfare)

# 복사본 생성
welfare <- raw_welfare
```

#### 1-3 데이터 검토
```{r}
head(welfare)
tail(welfare)
dim(welfare)
```

#### 1-4 특성 선택
```{r}
welfare <- rename(welfare,
                  sex = h10_g3,
                  birth = h10_g4, 
                  marriage = h10_g10, 
                  religion = h10_g11, 
                  income = p1002_8aq1, 
                  code_job = h10_eco9, 
                  code_region = h10_reg7)

welfare <- welfare[, c('sex','birth','marriage','religion','income','code_job','code_region')]
str(welfare)
```

# 2. 탐색적 데이터 분석

## 2-1 성별에 따른 월급 차이 
```{r}
# 변수 검토
class(welfare$sex)
table(welfare$sex)

# 성별 항목의 이름 변경 (1:male, 2:female)
welfare$sex <- ifelse(welfare$sex == 1,'male','female')
table(welfare$sex)

qplot(welfare$sex)
```
```{r}
# 월급 변수 검토 
class(welfare$income)
summary(welfare$income)

qplot(welfare$income)
qplot(welfare$income) + xlim(0,1000)
```

```{r}
# 월급 변수에 대한 전처리 : 이상치, 결측치
welfare$income <- ifelse(welfare$income %in% c(0,9999), NA, welfare$income)
table(is.na(welfare$income))
```
```{r}
# 성별에 따른 평균 급여
sex_income <- welfare %>% filter(!is.na (income)) %>% group_by(sex) %>% summarise(mean_income = mean(income))
sex_income
```

```{r}
# 최종 시각화 
# 빈도수 > 막대그래프

ggplot(data = sex_income, aes(sex, mean_income)) + geom_col()
# summarise(mean_income=mean(na.omit(income)))
```

#### 2-2 나이와 월급의 관계
 
 연령대 별로 월급이 얼만인지 
 
```{r}
### 변수 검토
class(welfare$birth)
table(welfare$birth)
class(welfare$income)
summary(welfare$income)
```

```{r}
welfare$age <- 2020-welfare$birth +1 

age_income <-welfare %>%
  filter(!is.na(income)) %>% group_by(age) %>% summarise(mean_income=mean(income))
age_income

ggplot(data=age_income, aes(x=age, y=mean_income)) + geom_col() 
```






























